### PR TITLE
Update README to point to Heroku's article

### PR DESCRIPTION
**Pull request by freeformz**
We support the features of this buildpack natively (w/o the need for a buildpack or file).

### CODE REVIEW

**Comment by ddollar** [comment]
Fwiw most users have reported liking the declarative file vs the configuration interface.

**Comment by freeformz** [comment]
FWIW: I like the file over the configuration interface as well.

**Comment by ddollar** [comment]
Tweaked on master

**Comment by freeformz** [comment]
Thanks. Should it not point to https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app though?

**Pull request closed without merging**
